- hosts: controlplane
  gather_facts: no
  become: false
  serial: 1
  tasks:
  - name: Upgrading Talos Linux | Setting facts
    set_fact:
      talosctl_opts: --insecure --talosconfig {{ inventory_dir }}/talosconfig -n {{ inventory_hostname }}

  - name: Upgrade Talos Linux | Starting the upgrade
    delegate_to: localhost
    ansible.builtin.command: talosctl {{ talosctl_opts }} upgrade --wait --preserve

- hosts: worker
  gather_facts: no
  become: false
  serial:
  - 1
  - "10%"
  - "20%"
  tasks:
  - name: Upgrading Talos Linux | Setting facts
    set_fact:
      talosctl_opts: --insecure --talosconfig {{ inventory_dir }}/talosconfig -n {{ inventory_hostname }} -e {{ inventory_hostname }}

  - name: Upgrade Talos Linux | Starting the upgrade
    delegate_to: localhost
    ansible.builtin.command: talosctl {{ talosctl_opts }} upgrade --wait --preserve
